#!/usr/bin/env python3
"""Create screen-sized opening images; retain full-resolution journal art and authored PNGs."""
import hashlib
import io
import json
import re
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'
sources = set(re.findall(r'/assets/[^\s\'\"]+\.png', (ROOT / 'src/content.ts').read_text()))
sources.update(item['src'] for item in json.loads((ROOT / 'src/header-art.json').read_text()).values())
sources.update('/assets/knit/' + name + '.png' for name in ['ground-knit', 'ivory-knit', 'hoho-tag', 'targetmol-pin'])
sources.add('/assets/chapters/music.png')
sources.update('/assets/ui/' + name + '.webp' for name in ['loading-knit-layered-desktop','loading-knit-layered-mobile','loading-cyclist-wool'])
output = PUBLIC / 'assets/web-images'
output.mkdir(parents=True, exist_ok=True)
mapping, records = {}, []
for url in sorted(sources):
    path = PUBLIC / url.lstrip('/')
    original = path.read_bytes()
    im = Image.open(io.BytesIO(original))
    source_size = im.size
    relief = path.name in ['ground-knit.png', 'ivory-knit.png']
    limit = (768 if 'cyclist' in url else 1672) if '/loading-' in url else 512 if relief else 384 if '/pins/' in url else 256 if path.name=='hoho-tag.png' else 512
    if '/journal/' not in url:
        im.thumbnail((limit, limit), Image.Resampling.LANCZOS)
    lossless = False
    quality = 92 if '/journal/' in url else 82 if '/loading-' in url else 86 if relief else 84
    encoded = io.BytesIO()
    im.save(encoded, format='WEBP', quality=quality, lossless=lossless, method=6, exact=True)
    data = encoded.getvalue()
    digest = hashlib.sha256(data).hexdigest()
    destination = output / f'{path.stem}.{digest[:12]}.webp'
    destination.write_bytes(data)
    mapping[url] = '/' + destination.relative_to(PUBLIC).as_posix()
    decoded = Image.open(io.BytesIO(data)).convert('RGBA')
    before, after = np.array(im.convert('RGBA')), np.array(decoded)
    assert decoded.size == im.size
    assert np.array_equal(before[:, :, 3], after[:, :, 3]), f'Alpha changed: {url}'
    if lossless:
        assert np.array_equal(before, after), f'Relief pixels changed: {url}'
    weight = before[:, :, 3:4].astype(np.float64) / 255
    error = (before[:, :, :3].astype(np.float64) - after[:, :, :3]) * weight
    records.append(dict(source=url, output=mapping[url], sourceSha256=hashlib.sha256(original).hexdigest(),
                        sha256=digest, sourceBytes=len(original), bytes=len(data), width=im.width,
                        height=im.height, sourceWidth=source_size[0], sourceHeight=source_size[1],
                        alphaExact=True, alphaReference='resized source', lossless=lossless, quality=quality,
                        compositedRgbRmse=float(np.sqrt(np.mean(error ** 2)))))
    print(f'{path.name}: {len(original):,} -> {len(data):,}', flush=True)
(ROOT / 'src/web-images.ts').write_text(
    '// Generated by scripts/prepare-web-images.py. Original assets stay in public for editing.\n'
    + 'export const webImages: Record<string, string> = ' + json.dumps(mapping, indent=2) + ';\n\n'
    + 'export const webImage = (source: string) => webImages[source] ?? source;\n')
(ROOT / 'assets/web-images-report.json').write_text(json.dumps(records, indent=2) + '\n')
print(json.dumps(dict(count=len(records), sourceBytes=sum(r['sourceBytes'] for r in records),
                      bytes=sum(r['bytes'] for r in records))))

# Keep the existing CSS composition and eight-frame animation; replace only URLs.
for filename in ['src/styles.css', 'index.html', 'src/SceneLoading.tsx']:
    target = ROOT / filename
    text = target.read_text()
    if filename == 'index.html':
        text = '\n'.join(line for line in text.split('\n') if not ('rel="preload"' in line and 'loading-knit-layered-' in line))
    for name in ['loading-knit-layered-desktop','loading-knit-layered-mobile','loading-cyclist-wool']:
        text = re.sub(r'/assets/(?:ui|web-images)/' + name + r'(?:\.[a-f0-9]{12})?\.webp', mapping['/assets/ui/'+name+'.webp'], text)
    target.write_text(text)

# Remove obsolete generated copies; every authored asset remains outside this directory.
active = {url.rsplit('/', 1)[-1] for url in mapping.values()}
for candidate in output.glob('*.webp'):
    if candidate.name not in active:
        candidate.unlink()
